-- Add all missing columns to products table
ALTER TABLE public.products
ADD COLUMN IF NOT EXISTS type TEXT,
ADD COLUMN IF NOT EXISTS brand TEXT,
ADD COLUMN IF NOT EXISTS store TEXT,
ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS is_consumed BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS purchase_date TIMESTAMPTZ;
